server:
  port: 3344
spring:
  application:
    name:  springcloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ChenShengqiang200/springcloud-config.git #GitHub上面的git仓库名字
#          不配也没关系，上面写全就好
#          search-paths:
#            - springcloud-config
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"